# Generated by Django 3.1 on 2020-08-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcrud', '0002_auto_20200822_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
