# Generated by Django 3.1 on 2020-08-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcrud', '0003_students_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
