# Generated by Django 3.1 on 2020-08-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcrud', '0004_auto_20200823_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='image',
            new_name='picture',
        ),
    ]
